language: en-US

reviews:
  profile: chill
  path_filters:
    - "!CHANGELOG.md"
    - "!dist/**"
  auto_review:
    ignore_title_keywords:
      - "chore(release)"
  tools:
    clippy:
      enabled: true
